-- create new schema
-- create database if not exists TP_PHP;
-- use TP_PHP;

-- Script de création de la base de données

PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS PARTICIPER;
DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS COMPOSER;
DROP TABLE IF EXISTS ASSOCIER;
DROP TABLE IF EXISTS REPONSE;
DROP TABLE IF EXISTS QUESTION;
DROP TABLE IF EXISTS QUIZ;

CREATE TABLE UTILISATEUR(
    EMAILU TEXT PRIMARY KEY NOT NULL,
    PASSWRD TEXT,
    NOMU TEXT,
    PRENOMU TEXT
);

CREATE TABLE QUIZ(
    IDQUIZ INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMQUIZ TEXT
);

CREATE TABLE PARTICIPER(
    EMAILU TEXT NOT NULL,
    IDQUIZ INT,
    POINTS INT,
    DATEPART DATETIME,
    PRIMARY KEY (EMAILU, IDQUIZ, DATEPART),
    FOREIGN KEY (EMAILU) REFERENCES UTILISATEUR(EMAILU),
    FOREIGN KEY (IDQUIZ) REFERENCES QUIZ(IDQUIZ)
);

CREATE TABLE QUESTION(
    NUMQ INTEGER PRIMARY KEY AUTOINCREMENT,
    INTITULE TEXT
);

CREATE TABLE COMPOSER(
    NUMQ INT,
    IDQUIZ INT,
    PRIMARY KEY (NUMQ, IDQUIZ),
    FOREIGN KEY (IDQUIZ) REFERENCES QUIZ(IDQUIZ),
    FOREIGN KEY (NUMQ) REFERENCES QUESTION(NUMQ)
);

CREATE TABLE REPONSE(
    NUMR INTEGER PRIMARY KEY AUTOINCREMENT,
    LIBELLE TEXT
);

CREATE TABLE ASSOCIER(
    NUMR INT,
    NUMQ INT,
    CORRECTE BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (NUMQ, NUMR),
    FOREIGN KEY (NUMQ) REFERENCES QUESTION(NUMQ),
    FOREIGN KEY (NUMR) REFERENCES REPONSE(NUMR)
);

