-- create new schema
-- create database if not exists TP_PHP;
-- use TP_PHP;

-- Script de création de la base de données

PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS PARTICIPER;
DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS COMPOSER;
DROP TABLE IF EXISTS ASSOCIER;
DROP TABLE IF EXISTS REPONSE;
DROP TABLE IF EXISTS QUESTION;
DROP TABLE IF EXISTS QUIZ;

CREATE TABLE UTILISATEUR(
    EMAILU TEXT PRIMARY KEY NOT NULL,
    PASSWRD TEXT,
    NOMU TEXT,
    PRENOMU TEXT
);

CREATE TABLE QUIZ(
    NOMQUIZ TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE PARTICIPER(
    IDPARTICIPER INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAILU TEXT NOT NULL,
    NOMQUIZ INT,
    POINTS INT,
    DATEPART DATETIME,
    FOREIGN KEY (EMAILU) REFERENCES UTILISATEUR(EMAILU),
    FOREIGN KEY (NOMQUIZ) REFERENCES QUIZ(NOMQUIZ)
);

CREATE TABLE QUESTION(
    NUMQ INTEGER PRIMARY KEY AUTOINCREMENT,
    INTITULE TEXT
);

CREATE TABLE COMPOSER(
    NUMQ INT,
    NOMQUIZ INT,
    PRIMARY KEY (NUMQ, NOMQUIZ),
    FOREIGN KEY (NOMQUIZ) REFERENCES QUIZ(NOMQUIZ),
    FOREIGN KEY (NUMQ) REFERENCES QUESTION(NUMQ)
);

CREATE TABLE REPONSE(
    NUMR INTEGER PRIMARY KEY AUTOINCREMENT,
    LIBELLE TEXT
);

CREATE TABLE ASSOCIER(
    NUMR INT,
    NUMQ INT,
    CORRECTE BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (NUMQ, NUMR),
    FOREIGN KEY (NUMQ) REFERENCES QUESTION(NUMQ),
    FOREIGN KEY (NUMR) REFERENCES REPONSE(NUMR)
);

