-- create new schema
create database if not exists TP_PHP;
use TP_PHP;

-- Script de création de la base de données
DROP TABLE IF EXISTS PARTICIPER
DROP TABLE IF EXISTS UTLISATEUR;
DROP TABLE IF EXISTS COMPOSER;
DROP TABLE IF EXISTS ASSOCIER;
DROP TABLE IF EXISTS REPONSE;
DROP TABLE IF EXISTS QUESTION;
DROP TABLE IF EXISTS QUIZZ;

CREATE TABLE UTLISATEUR(
    IDU INT PRIMARY KEY AUTO_INCREMENT,
    NOMU VARCHAR(15),
    PRENOMU VARCHAR(15)
)

CREATE TABLE QUIZZ(
    IDQUIZZ INT PRIMARY KEY AUTO_INCREMENT,
    NOMQUIZZ VARCHAR(15)
)

CREATE TABLE PARTICIPER(
    IDU INT,
    IDQUIZZ VARCHAR(15),
    POINTS INT,
    DATEPART DATETIME,
    PRIMARY KEY (IDU, IDQUIZZ, DATEPART)
)

CREATE TABLE QUESTION(
    NUMQ INT PRIMARY KEY AUTO_INCREMENT,
    INTITULE VARCHAR(30)
)

CREATE TABLE COMPOSER(
    NUMQ INT,
    IDQUIZZ INT,
    PRIMARY KEY (NUMQ, IDQUIZZ)
)

CREATE TABLE REPONSE(
    NUMR INT PRIMARY KEY AUTO_INCREMENT,
    LIBELLE VARCHAR(30)
)

CREATE TABLE ASSOCIER(
    NUMR INT,
    NUMQ INT,
    CORRECTE BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (NUMQ, NUMR)
)


-- Clés étrangères
ALTER TABLE PARTICIPER ADD FOREIGN KEY (IDU) REFERENCES UTILISATEUR(IDU);
ALTER TABLE PARTICIPER ADD FOREIGN KEY (IDQUIZZ) REFERENCES QUIZZ(IDQUIZZ);

ALTER TABLE COMPOSER ADD FOREIGN KEY (IDQUIZZ) REFERENCES QUIZZ(IDQUIZZ);
ALTER TABLE COMPOSER ADD FOREIGN KEY (NUMQ) REFERENCES QUESTION(NUMQ);

ALTER TABLE ASSOCIER ADD FOREIGN KEY (NUMQ) REFERENCES QUESTION(NUMQ);
ALTER TABLE ASSOCIER ADD FOREIGN KEY (NUMR) REFERENCES REPONSE(NUMR);
